//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTuned_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TvShow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TvShow()
        {
            this.Watchlists = new HashSet<Watchlist>();
        }
    
        public string Title { get; set; }
        public string Year { get; set; }
        public string Rating { get; set; }
        public string Genre { get; set; }
        public string Writers { get; set; }
        public string Directors { get; set; }
        public string Cast { get; set; }
        public string Synopsis { get; set; }
        public string Cover { get; set; }
        public string Trailer { get; set; }
        public Nullable<int> Seasons_Count { get; set; }
        public Nullable<System.DateTime> First_Episode_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Watchlist> Watchlists { get; set; }
    }
}
