//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTuned_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Watchlist
    {
        public string UserName { get; set; }
        public string MovieTitle { get; set; }
        public string TVShow { get; set; }
        public int Id { get; set; }
    
        public virtual Movie Movy { get; set; }
        public virtual TvShow TvShow1 { get; set; }
        public virtual User User { get; set; }
    }
}
